# Generated by Django 3.0.5 on 2020-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_users'),
        ),
    ]
