# Generated by Django 3.0.5 on 2020-04-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_auto_20200407_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='shit',
        ),
    ]
