# Generated by Django 3.0.5 on 2020-04-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0003_remove_relationship_shit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='user',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='action_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to='friendships.User'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to='friendships.User'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to='friendships.User'),
        ),
    ]
