# Generated by Django 3.0.5 on 2020-04-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0004_auto_20200407_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='action_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user_id', to='friendships.User'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one_id', to='friendships.User'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two_id', to='friendships.User'),
        ),
    ]
